[build]
command = "yarn rw deploy netlify"
publish = "web/dist"
functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://cecilianarchive.com/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.cecilianarchive.com/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true
